theme: jekyll-theme-slate
title: OpenWhistleblowing
description: Whistleblowing Software based on GlobaLeaks
show_downloads: false
twitter:
  username: openwhistleblow
github:
  repository_url: https://github.com/openwhistleblowing/openwhistleblowing
plugins:
- jekyll-seo-tag
- jekyll-sitemap
